In [1]:
print("Hello")

Hello

In [6]:
import pandas as pd
data_patent = pd.read_csv('./patents_with_samsung_2024_04_23_2_lines.csv')

In [7]:
display(data_patent)

,Unnamed: 0,Country,PatentNumber,ApplicationReference,Kind,Date,Abstract,OrganizationName,SummaryOfInvention,Claims,Year
0,1132,US,11963590,utility,B2,2024-04-23,A ring-type wearable device is disclosed. The ...,"SAMSUNG ELECTRONICS CO., LTD.",{'h-0001 - CROSS-REFERENCE TO RELATED APPLICAT...,['1. A ring-type wearable device comprising: a...,2024
1,1188,US,11963647,utility,B2,2024-04-23,A robot cleaner is provided. The robot cleaner...,"SAMSUNG ELECTRONICS CO., LTD.",{'h-0001 - CROSS-REFERENCE TO RELATED APPLICAT...,"['1. A robot cleaner comprising: a driver, inc...",2024

In [ ]:
import torch
torch.tensor([0.12,0.32]).cuda()

In [7]:
import torch
print(torch.version.cuda)
print(torch.__version__)

10.2
1.12.1+cu102

In [9]:
%pip install transformers

Collecting transformers
  Downloading transformers-4.40.2-py3-none-any.whl (9.0 MB)
     |████████████████████████████████| 9.0 MB 11.0 MB/s eta 0:00:01
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from transformers) (5.3.1)
Collecting huggingface-hub<1.0,>=0.19.3
  Downloading huggingface_hub-0.23.0-py3-none-any.whl (401 kB)
     |████████████████████████████████| 401 kB 69.2 MB/s eta 0:00:01
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from transformers) (3.8.0)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from transformers) (2.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/dist-packages (from transformers) (1.23.4)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.8/dist-packages (from transformers) (4.64.1)
Collecting regex!=2019.12.17
  Downloading regex-2024.5.10-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (777 kB)
     |████████████████████████████████| 777 kB 47.0 MB/s eta 0:00:01
Collecting safetensors>=0.4.1
  Downloading safetensors-0.4.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 35.5 MB/s eta 0:00:01
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from transformers) (21.3)
Collecting tokenizers<0.20,>=0.19
  Downloading tokenizers-0.19.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 86.7 MB/s eta 0:00:01
Collecting fsspec>=2023.5.0
  Downloading fsspec-2024.3.1-py3-none-any.whl (171 kB)
     |████████████████████████████████| 171 kB 85.8 MB/s eta 0:00:01
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (4.4.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->transformers) (1.25.8)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->transformers) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->transformers) (2019.11.28)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (2.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging>=20.0->transformers) (3.0.9)
Installing collected packages: fsspec, huggingface-hub, regex, safetensors, tokenizers, transformers
  WARNING: The script huggingface-cli is installed in '/home/c7361293/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script transformers-cli is installed in '/home/c7361293/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed fsspec-2024.3.1 huggingface-hub-0.23.0 regex-2024.5.10 safetensors-0.4.3 tokenizers-0.19.1 transformers-4.40.2
Note: you may need to restart the kernel to use updated packages.

In [22]:
%pip install transformers

Package                      Version
---------------------------- --------------------
absl-py                      1.3.0
ansible                      6.5.0
ansible-core                 2.13.5
anyio                        4.0.0
apturl                       0.5.2
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
arviz                        0.13.0
asttokens                    2.0.8
astunparse                   1.6.3
async-lru                    2.0.4
atomicwrites                 1.1.5
attrs                        23.1.0
autobahn                     17.10.1
Automat                      0.8.0
Babel                        2.13.1
backcall                     0.2.0
bcrypt                       3.1.7
beautifulsoup4               4.8.2
bleach                       6.1.0
blinker                      1.4
boto3                        1.25.1
botocore                     1.28.1
breezy                       3.0.2
Brlapi                       0.7.0
cachetools                   5.2.0
catkin-pkg                   1.0.0
catkin-pkg-modules           1.0.0
cbor                         1.0.0
certifi                      2019.11.28
cffi                         1.16.0
cftime                       1.6.2
chardet                      3.0.4
charset-normalizer           2.1.1
click                        8.0.4
cloud-init                   24.1.3
cloudpickle                  2.2.0
colorama                     0.4.3
comm                         0.1.4
command-not-found            0.3
configobj                    5.0.6
constantly                   15.1.0
contourpy                    1.0.5
cryptography                 2.8
cupshelpers                  1.0
cvxopt                       1.2.3
cycler                       0.11.0
Cython                       0.29.14
dbus-python                  1.2.16
debugpy                      1.8.0
decorator                    5.1.1
defer                        1.0.6
defusedxml                   0.6.0
deprecat                     2.1.1
Deprecated                   1.2.7
dgl                          0.9.1
dill                         0.3.6
distro                       1.4.0
distro-info                  0.23+ubuntu1.1
docutils                     0.16
dulwich                      0.19.15
empy                         3.3.2
entrypoints                  0.3
et-xmlfile                   1.0.1
exceptiongroup               1.1.3
executing                    1.1.1
fastimport                   0.9.8
fastjsonschema               2.18.1
fastprogress                 1.0.3
filelock                     3.8.0
fire                         0.4.0
flatbuffers                  22.10.26
fonttools                    4.38.0
fsspec                       2024.3.1
gast                         0.4.0
gensim                       4.2.0
google-auth                  2.13.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
gpg                          1.13.1
grpcio                       1.50.0
h5py                         3.7.0
html5lib                     1.0.1
httplib2                     0.14.0
huggingface-hub              0.23.0
hyperlink                    19.0.0
idna                         2.8
imageio                      2.22.2
importlib-metadata           5.0.0
importlib-resources          6.1.0
incremental                  16.10.1
ipykernel                    6.26.0
ipython                      8.5.0
ipython-genutils             0.2.0
jdcal                        1.0
jedi                         0.18.1
Jinja2                       3.1.2
jmespath                     1.0.1
joblib                       1.2.0
json5                        0.9.14
jsonpatch                    1.22
jsonpointer                  2.0
jsonschema                   4.19.1
jsonschema-specifications    2023.7.1
jupyter-client               8.5.0
jupyter-core                 5.4.0
jupyter-events               0.8.0
jupyter-lsp                  2.2.0
jupyter-server               2.9.1
jupyter-server-terminals     0.4.4
jupyterlab                   4.0.7
jupyterlab-pygments          0.2.2
jupyterlab-server            2.25.0
keras                        2.10.0
Keras-Preprocessing          1.1.2
keyring                      18.0.1
kiwisolver                   1.4.4
language-selector            0.1
laspy                        2.3.0
launchpadlib                 1.10.13
lazr.restfulclient           0.14.2
lazr.uri                     1.0.3
libclang                     14.0.6
llvmlite                     0.39.1
louis                        3.12.0
lxml                         4.9.1
lz4                          3.0.2+dfsg
macaroonbakery               1.3.1
Mako                         1.1.0
Markdown                     3.4.1
MarkupSafe                   2.1.1
matplotlib                   3.6.1
matplotlib-inline            0.1.6
mistune                      3.0.2
mlxtend                      0.21.0
more-itertools               4.2.0
mpi4py                       3.0.3
mpmath                       1.2.1
nbclient                     0.8.0
nbconvert                    7.9.2
nbformat                     5.9.2
nest-asyncio                 1.5.8
netCDF4                      1.6.1
netifaces                    0.10.4
networkx                     2.8.7
nltk                         3.4.5
nose                         1.3.7
notebook                     7.0.6
notebook-shim                0.2.3
numba                        0.56.3
numexpr                      2.8.4
numpy                        1.23.4
oauthlib                     3.1.0
olefile                      0.46
opencv-python                4.6.0.66
openpyxl                     3.0.3
opt-einsum                   3.3.0
overrides                    7.4.0
packaging                    21.3
pandas                       1.5.1
pandocfilters                1.5.0
parameterized                0.7.0
paramiko                     2.6.0
parso                        0.8.3
patsy                        0.5.1
pexpect                      4.6.0
pickleshare                  0.7.5
Pillow                       9.2.0
pip                          20.0.2
pkgutil-resolve-name         1.3.10
platformdirs                 3.11.0
plotly                       4.4.1
pluggy                       0.13.0
prometheus-client            0.17.1
prompt-toolkit               3.0.31
protobuf                     3.19.6
psutil                       5.9.3
ptyprocess                   0.7.0
pure-eval                    0.2.2
py                           1.8.1
py-ubjson                    0.14.0
py4j                         0.10.9.5
pyasn1                       0.4.2
pyasn1-modules               0.2.1
pybboxes                     0.1.5
pycairo                      1.16.2
pycparser                    2.21
pycrypto                     2.6.1
pycryptodomex                3.6.1
pycups                       1.9.73
pydot                        1.4.1
PyGithub                     1.43.7
Pygments                     2.13.0
PyGObject                    3.36.0
pygpu                        0.7.6
PyHamcrest                   1.9.0
PyJWT                        1.7.1
pymacaroons                  0.13.0
pymc3                        3.11.5
PyNaCl                       1.3.0
pyntcloud                    0.3.1
PyOpenGL                     3.1.0
pyOpenSSL                    19.0.0
pyparsing                    3.0.9
pypng                        0.0.20
PyQRCode                     1.2.1
PyQt5                        5.14.1
pyqtgraph                    0.11.0rc0
pyRFC3339                    1.1
pyrsistent                   0.15.5
pyserial                     3.4
pyspark                      3.3.1
pytest                       4.6.9
python-apt                   2.0.1+ubuntu0.20.4.1
python-dateutil              2.8.2
python-debian                0.1.36+ubuntu1.1
python-gitlab                2.0.1
python-gnupg                 0.4.5
python-json-logger           2.0.7
python-snappy                0.5.3
PyTrie                       0.2
pytz                         2022.5
PyWavelets                   1.4.1
pyxdg                        0.26
PyYAML                       5.3.1
pyzmq                        25.1.1
referencing                  0.30.2
regex                        2024.5.10
reportlab                    3.5.34
requests                     2.28.1
requests-oauthlib            1.3.1
requests-unixsocket          0.2.0
resolvelib                   0.8.1
retrying                     1.3.3
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
roman                        2.0.0
rosdep                       0.24.0
rosdep-modules               0.24.0
rosdistro                    0.9.1
rosdistro-modules            0.9.1
rosinstall                   0.7.8
rosinstall-generator         0.1.23
rospkg                       1.5.1
rospkg-modules               1.5.1
rpds-py                      0.10.6
rsa                          4.9
s3transfer                   0.6.0
safetensors                  0.4.3
sahi                         0.10.8
scikit-image                 0.19.3
scikit-learn                 1.1.3
scipy                        1.9.3
screen-resolution-extra      0.0.0
seaborn                      0.12.1
SecretStorage                2.3.1
semver                       2.13.0
Send2Trash                   1.8.2
sentencepiece                0.2.0
service-identity             18.1.0
setuptools                   45.2.0
shap                         0.41.0
Shapely                      1.8.5.post1
simplejson                   3.16.0
sip                          4.19.21
six                          1.14.0
sklearn-som                  1.1.0
slicer                       0.0.7
smart-open                   6.2.0
sniffio                      1.3.0
sos                          4.5.6
soupsieve                    1.9.5
spektral                     1.2.0
ssh-import-id                5.10
stack-data                   0.5.1
statsmodels                  0.11.1
sympy                        1.11.1
systemd-python               234
tensorboard                  2.10.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.10.0
tensorflow-estimator         2.10.0
tensorflow-io-gcs-filesystem 0.27.0
tensorrt                     10.0.1
tensorrt-dispatch            10.0.1
tensorrt-lean                10.0.1
termcolor                    2.0.1
terminado                    0.17.1
terminaltables               3.1.10
tesserocr                    2.5.0
Theano                       1.0.4
Theano-PyMC                  1.1.2
thop                         0.1.1.post2209072238
threadpoolctl                3.1.0
tifffile                     2022.10.10
tinycss2                     1.2.1
tokenizers                   0.19.1
tomli                        2.0.1
torch                        1.12.1
torchvision                  0.13.1
tornado                      6.3.3
tqdm                         4.64.1
traitlets                    5.5.0
transformers                 4.40.2
Twisted                      18.9.0
txaio                        2.10.0
typing-extensions            4.4.0
u-msgpack-python             2.1
ubuntu-drivers-common        0.0.0
ubuntu-pro-client            8001
ufw                          0.36
unattended-upgrades          0.1
urllib3                      1.25.8
vcstools                     0.1.42
wadllib                      1.3.3
wcwidth                      0.2.5
webencodings                 0.5.1
websocket-client             1.6.4
Werkzeug                     2.2.2
wheel                        0.34.2
word2vec                     0.11.1
wrapt                        1.14.1
wsaccel                      0.6.2
wstool                       0.1.18
xarray                       2022.10.0
xarray-einstats              0.3.0
xkit                         0.0.0
xlrd                         1.1.0
xlwt                         1.3.0
yellowbrick                  1.5
yolov5                       6.2.3
zipp                         1.0.0
zope.interface               4.7.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
%pip install sentencepiece

In [1]:
import torch
from transformers import LlamaTokenizer, LlamaForCausalLM

# Initialize the tokenizer and model
model_name_or_path = "/home/c7361293/triz_llm/llama-2-7b-chat/model"
tokenizer = LlamaTokenizer.from_pretrained(model_name_or_path)
model = LlamaForCausalLM.from_pretrained(model_name_or_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Move the model to the appropriate device
model.to(device)

/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading checkpoint shards: 100%|██████████████████| 3/3 [00:08<00:00,  2.93s/it]
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:146: UserWarning:
NVIDIA A40 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA A40 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

Using device: cuda

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (1): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (2): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (3): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (4): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (5): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (6): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (7): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (8): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (9): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (10): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (11): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (12): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (13): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (14): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (15): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (16): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (17): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (18): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (19): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (20): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (21): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (22): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
      (23): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()

In [4]:
import pandas as pd
data_patent = pd.read_csv('./patents_with_samsung_2024_04_23_2_lines.csv')

In [5]:
display(data_patent)

,Unnamed: 0,Country,PatentNumber,ApplicationReference,Kind,Date,Abstract,OrganizationName,SummaryOfInvention,Claims,Year
0,1132,US,11963590,utility,B2,2024-04-23,A ring-type wearable device is disclosed. The ...,"SAMSUNG ELECTRONICS CO., LTD.",{'h-0001 - CROSS-REFERENCE TO RELATED APPLICAT...,['1. A ring-type wearable device comprising: a...,2024
1,1188,US,11963647,utility,B2,2024-04-23,A robot cleaner is provided. The robot cleaner...,"SAMSUNG ELECTRONICS CO., LTD.",{'h-0001 - CROSS-REFERENCE TO RELATED APPLICAT...,"['1. A robot cleaner comprising: a driver, inc...",2024

In [ ]:
import torch
from transformers import LlamaTokenizer, LlamaForCausalLM


# Initialize the tokenizer and model
model_name_or_path = "/home/c7361293/triz_llm/llama-2-7b-chat/model"
tokenizer = LlamaTokenizer.from_pretrained(model_name_or_path)
model = LlamaForCausalLM.from_pretrained(model_name_or_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Move the model to the appropriate device
model.to(device)

# Function to summarize text
def summarize_abstract(text):

    torch.cuda.empty_cache()
    # prompt = f"Summarize this: {text} in 20 words"
    prompt = f"{text} \n Summarize the provided text focusing on the key improvement aimed at by the research, any potential drawbacks or degrading parameters mentioned, and any information on energy efficiency. The summary should clearly outline the main objectives, highlight any challenges or limitations if discussed, and note the presence or absence of energy efficiency details. Please keep the summary concise and output only the summary, ideally within five lines and start with 'Summary:'"
    # Check and set the padding token
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token  # Typically the EOS token can be used as pad token


    inputs = tokenizer(prompt, return_tensors="pt", padding=True, truncation=True)
    #  # Ensure that the attention mask and the pad token are set correctly
    # if 'attention_mask' not in inputs:
    #     inputs['attention_mask'] = torch.ones_like(inputs['input_ids'])
    # if 'pad_token_id' not in tokenizer.vocab:
    #     tokenizer.pad_token = tokenizer.eos_token

    inputs = inputs.to(device)
    
    output_sequences = model.generate(
        input_ids=inputs['input_ids'], 
        attention_mask=inputs['attention_mask'],
        max_length=5000, 
        num_return_sequences=1,
        do_sample=False  # Ensures more deterministic outputs
    )

    # print(tokenizer.decode(output_sequences, skip_special_tokens=True))
    text = tokenizer.decode(output_sequences[0], skip_special_tokens=True)
    summary_index = text.find("Summary:\n")
    summary = text
    if summary_index != -1:
        # Extract the text from "Begin Summary:" to the end of the string
         summary = text[summary_index:]

    return summary

# Apply summarization to each abstract and store results in a new column
summaries = []
for abstract in data_patent['Abstract']:
    summary = summarize_abstract(abstract)
    summaries.append(summary)

data_patent['SummaryofPatent'] = summaries
data_patent.to_csv('./summarized_patents/test.csv', index=False)